import { User } from '../interfaces'

/** Dummy user data. */
export const sampleUserData: User[] = [
  { id: 1,
  keyword: 'Blockchain',
  goal: 'technology',
  matches:18,
  search_status:'Done' },
  { id: 2,
    keyword: 'ReactJs',
    goal: 'technology',
    matches:18,
    search_status:'Done'  },
  {id: 3,
    keyword: 'NextJs',
    goal: 'technology',
    matches:18,
    search_status:'Done'  },
  { id: 4,
    keyword: 'Typescript',
    goal: 'technology',
    matches:18,
    search_status:'Done' },
    { id: 5,
      keyword: 'JavaScript',
      goal: 'technology',
      matches:18,
      search_status:'Done' },
      { id: 6,
        keyword: 'Django',
        goal: 'technology',
        matches:18,
        search_status:'Done' },
]

